# Generated by Django 6.0.4 on 2026-05-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jobseekerprofile_recruiterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
