"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vm_(3ufq)11!#sdnj)a(*olx+*866iq75xzhyj(6c(@tf)a8)4'

# SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['192.168.0.63', 'localhost', '127.0.0.1']

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",  # Admin UI customizer (must be before 'django.contrib.admin')
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'social_django',
    'django_celery_beat',

    # My apps
    'accounts',
    'jobs',
    'applications',
    'companies',
    'resumes',
    'notifications',
    'messaging',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',   
    'corsheaders.middleware.CorsMiddleware',  

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'social_django.middleware.SocialAuthExceptionMiddleware',
]


JAZZMIN_SETTINGS = {
    'site_title':        'JobPortal Admin',
    'site_header':       'JobPortal',
    'site_brand':        'JobPortal',
    'site_logo':         None,
    'welcome_sign':      'Welcome to JobPortal Admin',
    'copyright':         'JobPortal',

    'topmenu_links': [
        {'name': 'Home',      'url': 'admin:index'},
        {'name': 'View Site', 'url': '/', 'new_window': True},
        {'name': 'API',       'url': '/api/v1/jobs/', 'new_window': True},
    ],

    'usermenu_links': [
        {'name': 'View Site', 'url': '/', 'new_window': True},
    ],

    'show_sidebar':              True,
    'navigation_expanded':       True,
    'hide_apps':                 [],
    'hide_models':               [],

    'order_with_respect_to': [
        'accounts', 'companies', 'jobs',
        'applications', 'resumes', 'notifications',
    ],

    'icons': {
        'accounts.user':               'fas fa-users',
        'accounts.jobseekerprofile':   'fas fa-user-tie',
        'accounts.recruiterprofile':   'fas fa-briefcase',
        'companies.company':           'fas fa-building',
        'jobs.job':                    'fas fa-search',
        'jobs.savedjob':               'fas fa-bookmark',
        'applications.application':    'fas fa-file-alt',
        'applications.recruiterinvite':'fas fa-envelope',
        'resumes.resume':              'fas fa-file-pdf',
        'resumes.education':           'fas fa-graduation-cap',
        'resumes.experience':          'fas fa-history',
        'notifications.notification':  'fas fa-bell',
        'notifications.jobalert':      'fas fa-bullhorn',
        'auth.group':                  'fas fa-users-cog',
    },

    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children':'fas fa-circle',

    'related_modal_active': True,
    'custom_css':           None,
    'custom_js':            None,
    'show_ui_builder':      False,
    'changeform_format':    'horizontal_tabs',
}

JAZZMIN_UI_TWEAKS = {
    'navbar_small_text':  False,
    'footer_small_text':  False,
    'body_small_text':    False,
    'brand_small_text':   False,
    'brand_colour':       'navbar-success',
    'accent':             'accent-success',
    'navbar':             'navbar-dark',
    'no_navbar_border':   True,
    'navbar_fixed':       True,
    'layout_boxed':       False,
    'footer_fixed':       False,
    'sidebar_fixed':      True,
    'sidebar':            'sidebar-dark-success',
    'sidebar_nav_small_text':    False,
    'sidebar_disable_expand':    False,
    'sidebar_nav_child_indent':  True,
    'sidebar_nav_compact_style': False,
    'sidebar_nav_legacy_style':  False,
    'sidebar_nav_flat_style':    False,
    'theme':              'default',
    'dark_mode_theme':    None,
    'button_classes': {
        'primary':   'btn-primary',
        'secondary': 'btn-outline-secondary',
        'info':      'btn-info',
        'warning':   'btn-warning',
        'danger':    'btn-danger',
        'success':   'btn-success',
    },
}


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS (allow React dev server)
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
CORS_ALLOW_CREDENTIALS = True

# Redis & Celery
# ── Redis & Celery ─────────────────────────────────────────────────────────
REDIS_URL = 'redis://localhost:6379/0'

CELERY_BROKER_URL                         = REDIS_URL
CELERY_RESULT_BACKEND                     = REDIS_URL
CELERY_ACCEPT_CONTENT                     = ['json']
CELERY_TASK_SERIALIZER                    = 'json'
CELERY_RESULT_SERIALIZER                  = 'json'
CELERY_TIMEZONE                           = 'Asia/Kolkata'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BEAT_SCHEDULER                     = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_TASK_ALWAYS_EAGER                  = True
CELERY_TASK_EAGER_PROPAGATES              = True

# ── Cache ──────────────────────────────────────────────────────────────────
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_URL,
    }
}


# Email (Gmail SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = f'Nexhire <{config("EMAIL_HOST_USER")}>'

FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173')

# Media files (resumes, profile pics)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Social Auth
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.linkedin.LinkedinOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('GOOGLE_CLIENT_ID', default='')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('GOOGLE_CLIENT_SECRET', default='')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ── Production overrides ─────────────────────────────────────────────────────
PRODUCTION = config('PRODUCTION', default=False, cast=bool)

if PRODUCTION:
    DEBUG = False
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')

    # Security
    SECURE_PROXY_SSL_HEADER    = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT        = True
    SESSION_COOKIE_SECURE      = True
    CSRF_COOKIE_SECURE         = True

    # CORS for production frontend URL
    CORS_ALLOWED_ORIGINS = config(
        'CORS_ALLOWED_ORIGINS', default=''
    ).split(',')

    # Disable eager tasks in production (use real Celery)
    CELERY_TASK_ALWAYS_EAGER     = False
    CELERY_TASK_EAGER_PROPAGATES = False

    # Cloudinary for media files
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME'),
        'API_KEY':    config('CLOUDINARY_API_KEY'),
        'API_SECRET': config('CLOUDINARY_API_SECRET'),
    }



STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
